# Generated by Django 5.1.1 on 2024-09-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
